// <auto-generated />
using System;
using Dorywcza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dorywcza.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dorywcza.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            TypeOfJob = "Prace budowlane",
                            Workplace = "Katowice"
                        });
                });

            modelBuilder.Entity("Dorywcza.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("AgreementRodo")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 22,
                            AgreementRodo = true,
                            Comment = "Czy jest przerwa na piwo?",
                            Email = "example@example",
                            Experience = "3 lata na budowie",
                            Gender = "M",
                            Name = "Jan Kowalski",
                            Phone = "+48 000 000 000",
                            Qualification = "Certyfikat QWERTY, Ukończone technikum budowlane"
                        });
                });

            modelBuilder.Entity("Dorywcza.Models.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployerId");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            EmployerId = 1,
                            CompanyName = "ConstructNext",
                            Description = "Zajmujemy się budową obiektów różnego przeznaczenia"
                        });
                });

            modelBuilder.Entity("Dorywcza.Models.JobOffer", b =>
                {
                    b.Property<int>("JobOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AmountOfPlaces")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QualificationIsRequired")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("TimeFrame")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobOfferId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.ToTable("JobOffers");

                    b.HasData(
                        new
                        {
                            JobOfferId = 1,
                            AddDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            AmountOfPlaces = 1,
                            CategoryId = 1,
                            Description = "Praca na budowie sklepu spożywczego w 5-osobowym zespole",
                            EmployeeId = 1,
                            EmployerId = 1,
                            Name = "Praca budowlana na Zawodziu",
                            QualificationIsRequired = false,
                            Salary = 6000m,
                            State = true,
                            TimeFrame = "12.12.2019-14.12.2019"
                        });
                });

            modelBuilder.Entity("Dorywcza.Models.JobOffer", b =>
                {
                    b.HasOne("Dorywcza.Models.Category", "category")
                        .WithMany("JobOffers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Dorywcza.Models.Employee", "employee")
                        .WithMany("JobOffers")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Dorywcza.Models.Employer", "employer")
                        .WithMany("JobOffers")
                        .HasForeignKey("EmployerId");
                });
#pragma warning restore 612, 618
        }
    }
}
